GA2/GA2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from startpage.views import registerUser

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('startpage.urls')),
    path('registerUser/', registerUser, name="registerUser"),
    path('login/', auth_views.LoginView.as_view(template_name='startpage/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='startpage/logout.html'), name='logout'),
]

GA2/startpage/urls.py
from django.urls import path
from.views import registerUser, home

app_name = "startpage"


urlpatterns = [
    path('', home, name="home"),
]

GA2/startpage/models.py
from django.db import models

# Create your models here.

GA2/startpage/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def registerUser(request):
    if request.method == "POST":
        print(request.POST)
    else:
        form = UserCreationForm()
    return render(request, 'startpage/registerUser.html', {'form':form})

def home(request):
    return render(request, 'startpage/home.html')

GA2/startpage/templates/startpage/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/carousel/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="{% static 'InfoPage/css/carousel.css' %}" rel="stylesheet">
  </head>

  <body>
    <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
              <a class="navbar-brand" href="#">GA2 BASDUT</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'startpage:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'registerUser' %}">Register</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                </ul>
              </div>
            </nav>
          </header>
    <main role="main">

    {% block content %} {% endblock %}
  
    </main>
  </body>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="{% static 'InfoPage/js/bootstrap.bundle.min.js' %}"></script>
</html>

GA2/startpage/templates/startpage/home.html
{% extends "startpage/base.html" %}
{% load static %}

{% block content %}
  
{% endblock %}

GA2/startpage/templates/startpage/login.html
{% extends "startpage/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="content-section">
                <form action="" method="post">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Log In</legend>
                            {{form|crispy}}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit" id="login_btn">Login</button>
                    </div>
                </form>
                <div class="border-top pt-3">
                    <small class="text-muted">
                        Need Have An Account? <a class="ml-2" href="{% url 'registerUser' %}">Sign Up Now</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

GA2/startpage/templates/startpage/logout.html
{% extends "startpage/base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h2>You have been logged out</h2>    
            <div class="border-top pt-3">
                <small class="text-muted">
                    <a href="{% url 'login' %}">Log In Again</a>
                </small>
            </div>
        </div>
    </div>
</div>
{% endblock %}

GA2/startpage/templates/startpage/registerUser.html
{% extends "startpage/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="content-section">
                <form action="" method="post">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Join Today<br><br>
                        <h5>Allows product reviews and purchase</h5></legend>
                            {{form|crispy}}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit" id="signup_btn">Sign Up</button>
                    </div>
                </form>
                <div class="border-top pt-3">
                    <small class="text-muted">
                        Already Have An Account ? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}